# Java异常

## 基础概念

异常发生在程序运行期间，它影响了正常的程序执行流程

Java异常有三种类型

1. 检查性异常：在编译时不能被简单地忽略
2. 运行时异常：是可能被程序员避免的异常，可以在编译时忽略
3. 错误 ERROR：错误其实不是异常，而是脱离控制的问题，比如栈溢出

Java把异常当做对象来处理，并定义一个基类 java.lang.Throwable 作为所以异常的超类

==关键字== try、catch、finally、throw、throws

### 例子

```java
public class Outer {
    public static void main(String[] args) {
        System.out.println(11/0);
    }
}
// 异常报错  
	// Exception in thread "main" java.lang.ArithmeticException: / by zero
	// at src.com.bencyq.oop1.Outer.main(Outer.java:5)
```

## 异常处理机制

### 捕获异常

1. 语法
   try {	}
   catch(Throwable e){	}
   finally{	}
   
   ==e.printstackTrace== 打印原本应该报的异常信息
2. 实例一
    可以放多个 catch，但是大的异常类要放在后面，因为 catch 只能执行一次

```java
public class Outer {
    public static void main(String[] args) {
        int a = 1;
        int b = 0;
        try { // try 监控区域
            System.out.println(a / b);
        } 
        catch (ArithmeticException e) { // catch 捕获异常 (参数为想要捕获的异常类型)
            System.out.println("出现异常，变量b不为0");
        } 
        catch (Exception t) {
            System.out.println("被 Exception 捕获");
          }
        finally { // 善后工作 可以不要，经常用在IO流处理中，用于关闭IO流
            System.out.println("finally");
        }
        // 输出为   出现异常，变量b不为0  finally

        
        
        try{
        System.out.println(a / b);
        }
        catch(ArithmeticException e){
            e.printStackTrace();
        }
        // 输出为 java.lang.ArithmeticException: / by zero      at src.com.bencyq.oop1.Outer.main(Outer.java:8)
    }
}

```

3. catch() 里的参数为想要捕获的异常类型，参考下图：

   ![Java异常处理](D:\github本地仓库\java\基础知识\picture\image-20210215183521217.png)	